AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR repository for audio processing container images'

Parameters:
  env:
    Type: String
    Description: Environment name (dev, staging, prod)
  
Resources:
  # ECR Repository for container images
  AudioProcessingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub 'little-bit/audio-processing-${env}'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 tagged images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v", "latest"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Delete untagged images older than 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub 'little-bit-audio-processing-${env}'
        - Key: Environment
          Value: !Ref env
        - Key: Project
          Value: little-bit

Outputs:
  ECRRepository:
    Description: ECR repository URI
    Value: !GetAtt AudioProcessingRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepository'