AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified ECS Fargate cluster for testing'

Parameters:
  env:
    Type: String
    Description: Environment name (dev, staging, prod)
  
Resources:
  # ECS Cluster
  AudioProcessingCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'little-bit-audio-processing-${env}'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 4
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub 'little-bit-audio-processing-${env}'
        - Key: Environment
          Value: !Ref env
        - Key: Project
          Value: little-bit
        - Key: Service
          Value: audio-processing

  # CloudWatch Log Group for ECS tasks
  AudioProcessingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/little-bit-audio-processing-${env}'
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub 'little-bit-audio-processing-logs-${env}'
        - Key: Environment
          Value: !Ref env
        - Key: Project
          Value: little-bit

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref AudioProcessingCluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  ClusterArn:
    Description: ARN of the ECS cluster
    Value: !GetAtt AudioProcessingCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'

  LogGroupName:
    Description: CloudWatch log group name
    Value: !Ref AudioProcessingLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'